config/routes.rb
Rails.application.routes.draw do
  get 'planets/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root to: 'planets#index'

  resources :planets, only: [:index, :show, :create, :destroy] do
    resources :aliens, only: [:create, :new]
  end
end

app/models/alien.rb
class Alien < ApplicationRecord
  belongs_to :planet
  validates :name, presence: true, uniqueness: true
  validates :color, presence: true
  validates :height, numericality: { greater_than: 0 }
  validates :age, presence: true, numericality: { greater_than_or_equal_to: 0 }
  has_one_attached :photo
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/planet.rb
class Planet < ApplicationRecord
  has_many :aliens
  validates :name, presence: true
  validates :description, presence: true
  validates :size, length: { maximum: 500 }
  validates :alien_count, numericality: { greater_than_or_equal_to: 0 }
  validates :rings, numericality: { greater_than_or_equal_to: 3 }
  has_one_attached :photo
end

app/controllers/aliens_controller.rb
class AliensController < ApplicationController

  # def new
  #   @alien = Alien.new
  # end

  def create
    @planet = Planet.find(params[:planet_id])
    @alien = Alien.new(alien_params)
    @alien.planet = @planet
    if @alien.save
      redirect_to planet_path(@planet), notice: 'Successfully saved alien'
    else
      render 'planets/show', status: :unprocessable_entity
    end
  end

  private

  def alien_params
    params.require(:alien).permit(:name, :age, :color, :height, :photo)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/planets_controller.rb
class PlanetsController < ApplicationController
  def index
    @planets = Planet.all
    @planet = Planet.new
  end

  def show
    @planet = Planet.find(params[:id])
    @alien = Alien.new
  end

  def create
    @planet = Planet.new(strong_params)
    if @planet.save
      redirect_to @planet, notice: 'Planet was successfully created.'
    else
      @planets = Planet.all
      render 'index', status: :unprocessable_entity
    end
  end

  def destroy
    @planet = Planet.find(params[:id])
    if @planet.destroy
      redirect_to root_path, status: :see_other, notice: 'The planet was successfully deleted'
    else
      redirect_to root_index_path, status: :see_other, notice: 'Unsuccessful delete attempt'
    end
  end

  private

  def strong_params
    params.require(:planet).permit(:name, :description, :size, :alien_count, :rings, :photo)
  end
end

app/helpers/aliens_helper.rb
module AliensHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/planets_helper.rb
module PlanetsHelper
end

app/views/aliens/_form.html.erb
<div class="container m-3" style="position: sticky; top: 20px;">
  <h1 class="">Create an Alien</h1>
  <%= simple_form_for [@planet, @alien] do |f| %>
    <%= f.input :name %>
    <%= f.input :age %>
    <%= f.input :color %>
    <%= f.input :height %>
    <%= f.input :photo, as: :file %>
    <%= f.submit "Submit", class: 'btn btn-primary mt-3' %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsPlanetWithAliens</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/planets/_form.html.erb
<div class="container text-black control bg-transparent">
  <%= simple_form_for planet do |f| %>
    <%= f.input :name %>
    <%= f.input :description %>
    <%= f.input :size %>
    <%= f.input :alien_count %>
    <%= f.input :rings %>
    <%= f.input :photo, as: :file %>
    <%= f.submit "Submit", class: 'btn btn-primary mt-3' %>
  <% end %>
</div>

app/views/planets/index.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4), rgba(0,0,0,0.4)), url('<%= asset_path('solarsystem.jpg') %>');">
  <div class="container">
    <h1>Explore the <strong>beyond</strong> with <strong>me</strong>!</h1>
    <p>Space is massive and endless, just like our relationships!</p>
  </div>
</div>
<div class="container m-5 d-flex flex-wrap justify-content-center">
  <div class="row g-5">
    <h1>Planets</h1>
    <div class="col-7">
      <div class="cards">
        <% @planets.each do |planet| %>
          <div class="card-category d-flex" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= planet.photo.attached? ? cl_image_path(planet.photo.key) : image_path('planets.jpg')%>)">
            <%= link_to planet.name, planet_path(planet), class: 'text-decoration-none text-white' %>
            <div>
              <%= link_to planet_path(planet), data: { turbo_method: :delete, turbo_confirm: "Delete #{planet.name}?" }, class: 'text-white' do %>
                <i class="fa-solid fa-trash" style="color: white;"></i>
              <% end %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
    <div class="col-5 text-black">
      <h1>Create Planet</h1>
      <%= render 'planets/form', planet: @planet %>
    </div>
  </div>
</div>

app/views/planets/show.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4), rgba(0,0,0,0.4)), url('<%= asset_path('solarsystem.jpg') %>');">
  <div class="container text-white">
    <h1>Welcome to <%= @planet.name%>planet!</h1>
    <h1>Explore my <strong>features</strong> at your own <strong>risk</strong>!</h1>
    <p>Description: <%= @planet.description%></p>
    <p>size: <%= @planet.size%></p>
    <p>alien_count👽: <%= @planet.alien_count%></p>
    <p>Rings🪐: <%= @planet.rings%></p>
    <%= link_to planets_index_path, class: 'btn btn-primary' do%>
      <i class="fa-solid fa-earth-americas"></i>
      <span>See Planets</span>
    <% end %>
  </div>
</div>
<div class="d-flex flex-wrap col-8 container mt-5">
  <div class="justify-content-center" style="flex: 1">
    <% @planet.aliens.each do |alien| %>
      <div class="card text-center m-3 round-3 border border-4" style="width: 400px; border: 1px solid #ff5733;">
        <div class="card-category d-flex align-items-center" style="height: 250px; background: linear-gradient(135deg, #000000, #0f0c29, #302b63, #24243e);">
          <div class="card-body text-white text-start fs-6" style="flex: 1;">
            <p>Name: <%= alien.name %></p>
            <p>Age: <%= alien.age %></p>
            <p>Height: <%= alien.height %></p>
            <p>Color: <%= alien.color %></p>
          </div>
          <div class="card-img" style="flex: 2; background-size: cover; background-position: center; height: 100%; background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= alien.photo.attached? ? cl_image_path(alien.photo.key) : asset_path('alienn.jpg') %>)">
          </div>
        </div>
      </div>
    <% end %>
  </div>
  <div class="col-4" style="flex-1; width: 400px;">
    <%= render 'aliens/form', alien: @alien %>
  </div>
</div>